packages:
  - apps/*
  - packages/*

injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - sharp

overrides:
  "@types/react": 19.3.0
  "@types/react-dom": 19.3.0
